/*
 * Copyright 2016, GeoSolutions Sas.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// TODO take all plugins from ms2
module.exports = {
    plugins: {
        // custom plugins
        AttributionPlugin: require('./plugins/Attribution'),
        FeatureLoader: require('./plugins/FeatureLoader'),
        FooterPlugin: require('./plugins/Footer'),
        GeoNetworkLinkPlugin: require('./plugins/GeoNetworkLink'),
        HeaderPlugin: require('./plugins/Header'),
        LoginPlugin: require('./plugins/Login'),
        LoginModalPlugin: require('./plugins/LoginModal').default,
        PrivacyNote: require('./plugins/PrivacyNote'),
        // product plugins
        NavMenu: require('@mapstore/framework/product/plugins/NavMenu').default,
        AboutPlugin: require('@mapstore/framework/product/plugins/About').default,
        // framework  plugin
        AddGroupPlugin: require('@mapstore/framework/plugins/AddGroup').default,
        AnnotationsPlugin: require('@mapstore/framework/plugins/Annotations').default,
        AutoMapUpdatePlugin: require('@mapstore/framework/plugins/AutoMapUpdate').default,
        BackgroundSelectorPlugin: require('@mapstore/framework/plugins/BackgroundSelector').default,
        // BackgroundSwitcherPlugin: require('@mapstore/framework/plugins/BackgroundSwitcher').default, NOT_NEEDED
        BurgerMenuPlugin: require('@mapstore/framework/plugins/BurgerMenu').default,
        CRSSelectorPlugin: require('@mapstore/framework/plugins/CRSSelector').default,
        ContentTabs: require('@mapstore/framework/plugins/ContentTabs').default,
        ContextPlugin: require('@mapstore/framework/plugins/Context').default,
        ContextCreatorPlugin: require('@mapstore/framework/plugins/ContextCreator').default,
        ContextManagerPlugin: require('@mapstore/framework/plugins/contextmanager/ContextManager').default,
        CookiePlugin: require('@mapstore/framework/plugins/Cookie').default,
        CreateNewMapPlugin: require('@mapstore/framework/plugins/CreateNewMap').default,
        Dashboard: require('@mapstore/framework/plugins/Dashboard').default,
        DashboardEditor: require('@mapstore/framework/plugins/DashboardEditor').default,
        DashboardSavePlugin: require('@mapstore/framework/plugins/DashboardSave').DashboardSave,
        DashboardSaveAsPlugin: require('@mapstore/framework/plugins/DashboardSave').DashboardSaveAs,
        DashboardsPlugin: require('@mapstore/framework/plugins/Dashboards').default,
        DetailsPlugin: require('@mapstore/framework/plugins/Details').default,
        DrawerMenuPlugin: require('@mapstore/framework/plugins/DrawerMenu').default,
        ExpanderPlugin: require('@mapstore/framework/plugins/Expander').default,
        FeatureEditorPlugin: require('@mapstore/framework/plugins/FeatureEditor').default,
        FeaturedMaps: require('@mapstore/framework/plugins/FeaturedMaps').default,
        FeedbackMaskPlugin: require('@mapstore/framework/plugins/FeedbackMask').default,
        FilterLayerPlugin: require('@mapstore/framework/plugins/FilterLayer').default,
        // FloatingLegendPlugin: require('@mapstore/framework/plugins/FloatingLegend').default, NOT_NEEDED
        FullScreenPlugin: require('@mapstore/framework/plugins/FullScreen').default,
        GeoStoryPlugin: require('@mapstore/framework/plugins/GeoStory').default,
        GeoStoriesPlugin: require('@mapstore/framework/plugins/GeoStories').default,
        GeoStoryEditorPlugin: require('@mapstore/framework/plugins/GeoStoryEditor').default,
        GeoStorySavePlugin: require('@mapstore/framework/plugins/GeoStorySave').GeoStorySave,
        GeoStorySaveAsPlugin: require('@mapstore/framework/plugins/GeoStorySave').GeoStorySaveAs,
        GeoStoryNavigationPlugin: require('@mapstore/framework/plugins/GeoStoryNavigation').default,
        GlobeViewSwitcherPlugin: require('@mapstore/framework/plugins/GlobeViewSwitcher').default,
        GoFull: require('@mapstore/framework/plugins/GoFull').default,
        // GridContainerPlugin: require('@mapstore/framework/plugins/GridContainer').default, NOT NEEDED (bound to theme ThemeSwitcherPlugin and MapTypePlugin)
        GroupManagerPlugin: require('@mapstore/framework/plugins/manager/GroupManager').default,
        HelpLinkPlugin: require('@mapstore/framework/plugins/HelpLink').default,
        HelpPlugin: require('@mapstore/framework/plugins/Help').default,
        HomePlugin: require('@mapstore/framework/plugins/Home').default,
        IdentifyPlugin: require('@mapstore/framework/plugins/Identify').default,
        LanguagePlugin: require('@mapstore/framework/plugins/Language').default,
        LocatePlugin: require('@mapstore/framework/plugins/Locate').default,
        ManagerMenuPlugin: require('@mapstore/framework/plugins/manager/ManagerMenu').default,
        ManagerPlugin: require('@mapstore/framework/plugins/manager/Manager').default,
        MapEditorPlugin: require('@mapstore/framework/plugins/MapEditor').default,
        MapExportPlugin: require('@mapstore/framework/plugins/MapExport').default,
        MapFooterPlugin: require('@mapstore/framework/plugins/MapFooter').default,
        MapImportPlugin: require('@mapstore/framework/plugins/MapImport').default,
        MapLoadingPlugin: require('@mapstore/framework/plugins/MapLoading').default,
        MapPlugin: require('@mapstore/framework/plugins/Map').default,
        MapSearchPlugin: require('@mapstore/framework/plugins/MapSearch').default,
        MapsPlugin: require('@mapstore/framework/plugins/Maps').default,
        MapCatalogPlugin: require('@mapstore/framework/plugins/MapCatalog').default,
        MapTemplatesPlugin: require('@mapstore/framework/plugins/MapTemplates').default,
        MeasurePlugin: require('@mapstore/framework/plugins/Measure').default,
        MediaEditorPlugin: require('@mapstore/framework/plugins/MediaEditor').default,
        MetadataExplorerPlugin: require('@mapstore/framework/plugins/MetadataExplorer').default,
        MousePositionPlugin: require('@mapstore/framework/plugins/MousePosition').default,
        NotificationsPlugin: require('@mapstore/framework/plugins/Notifications').default,
        OmniBarPlugin: require('@mapstore/framework/plugins/OmniBar').default,
        PlaybackPlugin: require('@mapstore/framework/plugins/Playback').default,
        PrintPlugin: require('@mapstore/framework/plugins/Print').default,
        QueryPanelPlugin: require('@mapstore/framework/plugins/QueryPanel').default,
        RedirectPlugin: require('@mapstore/framework/plugins/Redirect').default,
        RedoPlugin: require('@mapstore/framework/plugins/History').default,
        RulesDataGridPlugin: require('@mapstore/framework/plugins/RulesDataGrid').default,
        RulesEditorPlugin: require('@mapstore/framework/plugins/RulesEditor').default,
        RulesManagerFooter: require('@mapstore/framework/plugins/RulesManagerFooter').default,
        SaveAsPlugin: require('@mapstore/framework/plugins/SaveAs').default,
        SavePlugin: require('@mapstore/framework/plugins/Save').default,
        ScaleBoxPlugin: require('@mapstore/framework/plugins/ScaleBox').default,
        ScrollTopPlugin: require('@mapstore/framework/plugins/ScrollTop').default,
        SearchPlugin: require('@mapstore/framework/plugins/Search').default,
        SearchServicesConfigPlugin: require('@mapstore/framework/plugins/SearchServicesConfig').default,
        SettingsPlugin: require('@mapstore/framework/plugins/Settings').default,
        SharePlugin: require('@mapstore/framework/plugins/Share'),
        SnapshotPlugin: require('@mapstore/framework/plugins/Snapshot').default,
        StyleEditorPlugin: require('@mapstore/framework/plugins/StyleEditor').default,
        TOCItemsSettingsPlugin: require('@mapstore/framework/plugins/TOCItemsSettings').default,
        TOCPlugin: require('@mapstore/framework/plugins/TOC').default,
        ThematicLayerPlugin: require('@mapstore/framework/plugins/ThematicLayer').default,
        // ThemeSwitcherPlugin: require('../plugins/ThemeSwitcher').default, NOT_NEEDED
        TimelinePlugin: require('@mapstore/framework/plugins/Timeline').default,
        ToolbarPlugin: require('@mapstore/framework/plugins/Toolbar').default,
        TutorialPlugin: require('@mapstore/framework/plugins/Tutorial').default,
        UndoPlugin: require('@mapstore/framework/plugins/History').default,
        UserExtensionsPlugin: require('@mapstore/framework/plugins/UserExtensions').default,
        UserManagerPlugin: require('@mapstore/framework/plugins/manager/UserManager').default,
        UserSessionPlugin: require('@mapstore/framework/plugins/UserSession').default,
        VersionPlugin: require('@mapstore/framework/plugins/Version').default,
        WFSDownloadPlugin: require('@mapstore/framework/plugins/WFSDownload').default,
        WidgetsBuilderPlugin: require('@mapstore/framework/plugins/WidgetsBuilder').default,
        WidgetsPlugin: require('@mapstore/framework/plugins/Widgets').default,
        WidgetsTrayPlugin: require('@mapstore/framework/plugins/WidgetsTray').default,
        ZoomAllPlugin: require('@mapstore/framework/plugins/ZoomAll').default,
        ZoomInPlugin: require('@mapstore/framework/plugins/ZoomIn').default,
        ZoomOutPlugin: require('@mapstore/framework/plugins/ZoomOut').default
    },
    requires: {
        ReactSwipe: require('react-swipeable-views').default,
        SwipeHeader: require('@mapstore/framework/components/data/identify/SwipeHeader').default
    }
};
